### ISSUE TITLE
Package doesn't work

### ISSUE THREAD

**Issue by edmundmiller** [twitchy-ears/org-roam-sbl-show-broken-links#1]
I'm getting an error using either function in the package

```org-roam-sbl-scan-for-broken-links: Symbol’s function definition is void: equalp```

Let me know what other information you'd like!

**Comment by twitchy-ears** [comment]
Apologies, I forgot I was using the cl package for things but not actually listing it as a requirement.  If you try there should be a fresh commit that works better for you.

**Comment by edmundmiller** [comment]
Awesome it works! Thanks for the quick response!

**Comment by twitchy-ears** [comment]
No worries, glad that's fixed and thanks for the prompt bug report.  Let me know if you find any more.
