### ISSUE TITLE
org-roam-sbl-conceptually-blank-file-p doesn't handle links to directories

### ISSUE THREAD

**Issue by rrix** [twitchy-ears/org-roam-sbl-show-broken-links#3]
https://github.com/twitchy-ears/org-roam-sbl-show-broken-links/blob/fd70eab7305efebec52f58eb9ce9faa2c24cdae2/org-roam-sbl-show-broken-links.el#L99

if `canonpath` is a directory, this function will try to call `insert-file-contents` on it, and this fails :) I patched it at home replacing the check with:

```
(and (file-exists-p canonpath)
             (not (file-directory-p canonpath)))
```

thanks, this is a nice and useful thing, cheers.

**Comment by twitchy-ears** [comment]
Ah I did not anticipate this behaviour from file-exists-p, thanks for that I've replicated your fix, glad you're finding it useful :)

Can you check that and let me know?

**Comment by twitchy-ears** [comment]
Believe to be fixed.
